create table scores (
	starttime long primary key,
	name text,
	death text,
	ver_major integer,
	ver_minor integer,
	patchlevel integer,
	points long,
	deathdnum integer,
	deathlev integer,
	maxlvl integer,
	hp integer,
	maxhp integer,
	deaths integer,
	deathdate long,
	birthdate long,
	uid integer,
	role text,
	race text,
	gender text,
	align text,
	realtime long,
	endtime long
);
