RECOVER := $(CURDIR)/recover.exe
MAKEDEFS := $(CURDIR)/makedefs.exe
DGN_COMP := $(CURDIR)/dgn_comp.exe
LEV_COMP := $(CURDIR)/lev_comp.exe
RX := $(CURDIR)/rx.exe
BOARD := $(CURDIR)/board.exe

MAKEDEFS_SOURCES := makedefs.c
MAKEDEFS_SOURCES := $(MAKEDEFS_SOURCES:%=$(CURDIR)/%)
MAKEDEFS_OBJECTS := $(MAKEDEFS_SOURCES:.c=.o)
MAKEDEFS_DEPS := $(MAKEDEFS_SOURCES:.c=.d)

RECOVER_SOURCES := recover.c
RECOVER_SOURCES := $(RECOVER_SOURCES:%=$(CURDIR)/%)
RECOVER_OBJECTS := $(RECOVER_SOURCES:.c=.o)
RECOVER_DEPS := $(RECOVER_SOURCES:.c=.d)

ALLOC_SOURCES := $(SRCDIR)/alloc.c $(CURDIR)/panic.c
ALLOC_OBJECTS := $(ALLOC_SOURCES:.c=.o)
ALLOC_DEPS := $(ALLOC_SOURCES:.c=.d)

DGN_YACC_SOURCES := $(CURDIR)/dgn_yacc.y
DGN_YACC_GENERATED_SOURCES := $(DGN_YACC_SOURCES:.y=.c)
DGN_YACC_DEPS := $(DGN_YACC_GENERATED_SOURCES:.c=.d)
DGN_YACC_OBJECTS := $(DGN_YACC_GENERATED_SOURCES:.c=.o)

DGN_LEX_SOURCES := $(CURDIR)/dgn_lex.l
DGN_LEX_GENERATED_SOURCES := $(DGN_LEX_SOURCES:.l=.c)
DGN_LEX_DEPS := $(DGN_LEX_GENERATED_SOURCES:.c=.d)
DGN_LEX_OBJECTS := $(DGN_LEX_GENERATED_SOURCES:.c=.o)

DGN_COMP_SOURCES := $(CURDIR)/dgn_main.c
DGN_COMP_OBJECTS := $(DGN_COMP_SOURCES:.c=.o)
DGN_COMP_DEPS := $(DGN_COMP_SOURCES:.c=.d)

LEV_YACC_SOURCES := $(CURDIR)/lev_yacc.y
LEV_YACC_GENERATED_SOURCES := $(LEV_YACC_SOURCES:.y=.c)
LEV_YACC_DEPS := $(LEV_YACC_GENERATED_SOURCES:.c=.d)
LEV_YACC_OBJECTS := $(LEV_YACC_GENERATED_SOURCES:.c=.o)

LEV_LEX_SOURCES := $(CURDIR)/lev_lex.l
LEV_LEX_GENERATED_SOURCES := $(LEV_LEX_SOURCES:.l=.c)
LEV_LEX_DEPS := $(LEV_LEX_GENERATED_SOURCES:.c=.d)
LEV_LEX_OBJECTS := $(LEV_LEX_GENERATED_SOURCES:.c=.o)

LEV_COMP_SOURCES := $(CURDIR)/lev_main.c
LEV_COMP_OBJECTS := $(LEV_COMP_SOURCES:.c=.o)
LEV_COMP_DEPS := $(LEV_COMP_SOURCES:.c=.d)

RX_SOURCES := $(CURDIR)/rx.c $(CURDIR)/list.c
RX_OBJECTS := $(RX_SOURCES:.c=.o)
RX_DEPS := $(RX_SOURCES:.c=.d)

BOARD_SOURCES := $(CURDIR)/board.c $(CURDIR)/list.c
BOARD_OBJECTS := $(BOARD_SOURCES:.c=.o)
BOARD_DEPS := $(BOARD_SOURCES:.c=.d)
